services:
  postgres:
    image: postgres:16
    container_name: expense_tracker_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: expense_tracker_pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - 5050:80
    depends_on:
      - postgres
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense_tracker_api
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres



volumes:
  pgdata:

